###########################################################################
# Name: chunk_collections.py
# 
# This file generates four chunk collections using the chunking methods
# defined in `iii_chunking.py`:
#   - fixed_token_chunks 
#   - recursive_chunks
#   - sentence_chunks
#   - semantic_chunks
#
# The generated chunk collections are shared by BM25 indexing and dense
# indexing to ensure that both retrieval methods use exactly the same
# chunks and metadata.
##########################################################################

from datasets import load_from_disk
import pickle
import re

from ii_chunking import (
    fixed_size_token,
    recursive,
    fixed_size_sentence,
    semantic
)


# ======================================================================
# SETTING. DEFINE PAPER IDS FROM THE ORIGINAL DATASET 
# 
# Stores the original PubMed dataset indices of the 10 selected papers.
# These IDs are added to each chunk record so that every generated chunk
# can be traced back to its source paper in the original dataset.
# ======================================================================
paper_ids = [2146, 10884, 13995, 17302, 19577, 21665, 24216, 25475, 899, 1625]

# ======================================================================
# STEP 1. LOAD THE CUSTOM CORPUS
# 
# Loads and extracts the 10 selected papers' full article texts.
# ======================================================================

custom_corpus = load_from_disk("custom_corpus")

documents = []
for paper in custom_corpus:
    no_cite = re.sub(r'(?<=\D)\.(\d+)', '.', paper["article"]) # Remove most citation numbers, because they confuse the sentence splitter
    normalize_whitespace = re.sub(r"\s+", " ", no_cite).strip()
    documents.append(normalize_whitespace)

if len(documents) != len(paper_ids):
    raise ValueError(
        "The number of documents must match the number of paper IDs."
    )


# ======================================================================
# STEP 2. APPLY A CHUNKING METHOD TO ALL DOCUMENTS
# 
# Applies one selected chunking function to every document in the corpus.
# This helper function is used for fixed-token, recursive, and 
# sentence chunking that accept size and overlap parameters.
#
# Parameters:
#   documents: 
#       A list of full article texts.
#
#   chunking_function: 
#       One of the chunking functions imported from `iii_chunking.py`.
#
#   method_name: 
#       The name of the selected chunking method.
#
#   size: 
#       The chunk-size argument passed to the chunking function.
#       It represents either tokens or sentences, depending on the method.
#
#   overlap: 
#       The overlap argument passed to the chunking function.
#
# Returns:
#   A list of chunk records that contains the chunk text and metadata
#   that identifies its source document, chunk, and method.
# ======================================================================

def create_chunk_records(documents, chunking_function, method_name, size, overlap):

    chunk_records = []

    # Process each document using the selected chunking function.
    for document_id, document in enumerate(documents):
        document_chunks = chunking_function(document, size, overlap)

        # Store each chunk together with its document and chunk metadata.
        for chunk_id, chunk in enumerate(document_chunks):
            chunk_records.append({
                "text": chunk["text"],
                "document_id": document_id,
                "paper_id": paper_ids[document_id],
                "chunk_id": chunk_id,
                "method": method_name,
                "start": chunk["start"],
                "end": chunk["end"]
            })

    return chunk_records


# ======================================================================
# STEP 3. APPLY SEMANTIC CHUNKING TO ALL DOCUMENTS
#
# Applies semantic chunking separately to every document in the corpus 
# since it uses `target_num_chunks` instead of chunk size and overlap.
# 
# For future comparison purposes, each document is divided into 
# approximately the same number of semantic chunks as the fixed-token 
# method produced for that document.
#
# Parameters:
#   documents:
#       A list of full article texts.
#
#   reference_chunks:
#       Chunk records generated by the fixed-token method.
#
# Returns:
#   A list of semantic chunk records with source metadata.
# ======================================================================

def create_semantic_chunk_records(documents, reference_chunks):

    semantic_chunk_records = []

    for document_id, document in enumerate(documents):

        # Uses the number of fixed-token chunks for this document
        # as the target number of semantic chunks.
        target_num_chunks = sum(
            1
            for chunk in reference_chunks
            if chunk["document_id"] == document_id
        )

        # Applies semantic chunking on this document using `target_num_chunk`.
        document_chunks = semantic(document, target_num_chunks=target_num_chunks)

        for chunk_id, chunk in enumerate(document_chunks):
            semantic_chunk_records.append({
                "text": chunk["text"],
                "document_id": document_id,
                "paper_id": paper_ids[document_id],
                "chunk_id": chunk_id,
                "method": "semantic",
                "start": chunk["start"],
                "end": chunk["end"]
            })

    return semantic_chunk_records


# ======================================================================
# STEP 4. GENERATE THE FOUR CHUNK COLLECTIONS
#
# Generates four chunk collections, one for each chunking method.
# Each collection contains all chunks generated from every document in 
# the corpus using the corresponding chunking method.
#
# For a fair comparison across chunking methods:
#
# - Fixed-token and recursive chunking use the same token size and overlap. 
#
# - Sentence chunking currently uses four sentences per chunk.
#   This value is intended to approximate the target token lengh but has
#   not yet been statistically validated.
# 
# - Semantic chunking uses the number of fixed-token chunks as its target
#   number of chunks.
# ======================================================================

fixed_token_chunks = create_chunk_records(
    documents=documents,
    chunking_function=fixed_size_token,
    method_name="fixed_token",
    size=125,
    overlap=0.25
)

recursive_chunks = create_chunk_records(
    documents=documents,
    chunking_function=recursive,
    method_name="recursive",
    size=125,
    overlap=0.25
)

sentence_chunks = create_chunk_records(
    documents=documents,
    chunking_function=fixed_size_sentence,
    method_name="sentence",
    size=4,
    overlap=0
)

semantic_chunks = create_semantic_chunk_records(
    documents=documents,
    reference_chunks=fixed_token_chunks
)


# ======================================================================
# STEP 5. STORE THE FOUR CHUNK COLLECTIONS
#
# Stores the four chunk collections in one pickle file so BM25 indexing
# and dense indexing can use the exact same generated chunks.
# ======================================================================

chunk_collections = {
    "fixed_token": fixed_token_chunks,
    "recursive": recursive_chunks,
    "sentence": sentence_chunks,
    "semantic": semantic_chunks
}

with open("chunk_collections.pkl", "wb") as file:
    pickle.dump(chunk_collections, file)

print("\nFour chunk collections are successfully saved to chunk_collections.pkl\n")