###########################################################################
# Name: v_dense_retrieval.py
# 
# This file performs dense retrieval using the chunk embeddings and metadata
# previously generated in `iv_dense_indexing.py`.
# 
# For each evaluation query, the corresponding embedding model is loaded 
# and used to generate a query embedding. The query embedding and all
# stored chunk embeddings are then normalized.
# 
# Cosine similarity is computed between the normalized query embedding and
# all normalized chunk embeddings. The chunks are ranked by their similarity
# scores, and the top-k chunks are returned together with their text, 
# metadata, similarity scores, and retrieval ranks.
##########################################################################


import pickle
import numpy as np
import torch
import json

from openai import OpenAI
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModel


# ======================================================================
# STEP 1. LOAD THE SAVED DENSE INDEXES
# 
# Loads the chunk embeddings and their associated metadata generated by
# `iv_dense_indexing.py`.
# 
# The data structure of `dense_indexes.pkl` is like:
#   dense_indexes[embedding_model][chunking_method]
#       -> list of indexed chunk records
# 
#   Each indexted chunk record contains the original chunk text and metadata,
#   and its generated embedding:
#       {
#           "text": ...,
#           "document_id": ...,
#           "paper_id": ...,
#           "chunk_id": ...,
#           "method": ...,
#           "embedding": ...
#       }
# ======================================================================

with open("dense_indexes.pkl", "rb") as file:
    dense_indexes = pickle.load(file)


# ======================================================================
# STEP 2. LOAD AN EMBEDDING MODEL
# 
# Loads the selected embedding model once so that it can be reused for
# all queries.
# 
# Parameters:
#   embedding_model:
#       The name of the embedding model to load.
# 
# Returns:
#   A dictionary that contains the model and any required tokenizer/client.
# ======================================================================

def load_embedding_model(embedding_model):
    
    if embedding_model == "OpenAI":
        return {
            "client": OpenAI()
            }
    
    elif embedding_model == "BioBERT":
        return {
            "model": SentenceTransformer(
                "pritamdeka/S-BioBert-snli-multinli-stsb"
            )
        }
    
    elif embedding_model == "BGE":
        return {
            "model": SentenceTransformer("BAAI/bge-large-en-v1.5")
        }

    # Note: MedCPT uses its Query Encoder for questions 
    #       instead of the Article Encoder that's used during dense indexing.
    elif embedding_model == "MedCPT":
        tokenizer = AutoTokenizer.from_pretrained(
            "ncbi/MedCPT-Query-Encoder"
        )


        model = AutoModel.from_pretrained(
            "ncbi/MedCPT-Query-Encoder"
        )

        model.eval()

        return {
            "tokenizer": tokenizer,
            "model": model
        }

    else:
        raise ValueError(
            f"Error: Unsupported embedding model: {embedding_model}"
        )
    

# ======================================================================
# STEP 3. GENERATE A QUERY EMBEDDING
# 
# Converts a query into an embedding using the selected embedding model.
# 
# Parameters:
#   query:
#       The question to embed.
# 
#   embedding_model:
#       The name of the selected embedding model.
# 
#   model_resources:
#       The loaded model, tokenizer, or OpenAI client.
# 
# Returns:
#   A one-dimensional NumPy array that contains the query embedding.
# ======================================================================

def get_query_embedding(query, embedding_model, model_resources) -> np.ndarray:

    if embedding_model == "OpenAI":

        response = model_resources["client"].embeddings.create(
            model="text-embedding-3-large",
            input=query
        )

        query_embedding = np.array(
            response.data[0].embedding,
            dtype=np.float32
        )
    
    elif embedding_model == "BGE": 

        # BGE performs better for retrieval when the query is prefixed with a
        # retrieval instruction.
        query_embedding = model_resources["model"].encode(
            "Represent this sentence for searching relevant passages: " 
            + query,
            normalize_embeddings=True,
            convert_to_numpy=True
        )

        query_embedding = query_embedding.astype(np.float32)

    elif embedding_model == "BioBERT":

        query_embedding = model_resources["model"].encode(
            query,
            normalize_embeddings=True,
            convert_to_numpy=True
        )

    elif embedding_model == "MedCPT":

        tokenizer = model_resources["tokenizer"]
        model = model_resources["model"]

        # Tokenizes the query into the format required by the MedCPT encoder.
        encoded_query = tokenizer(
            query,
            truncation=True,
            padding=True,
            return_tensors="pt",
            max_length=512
        )

        # Generates the query embedding using the [CLS] token representation.
        with torch.no_grad():
            query_embedding = model(
                **encoded_query
            ).last_hidden_state[:, 0, :]

        # Removes the batch dimension and converts the tensor to a NumPy array.
        query_embedding = (
            query_embedding
            .squeeze(0)
            .cpu()
            .numpy()
            .astype(np.float32)
        )

        query_embedding = normalize_vector(query_embedding)

    else:
        raise ValueError(
            f"Error: Unsupported embedding model: {embedding_model}"
        )

    return query_embedding


# ======================================================================
# STEP 4. NORMALIZE AN EMBEDDING VECTOR
# 
# Converts an embedding vector to unit length so that embeddings from
# different models can be compared consistently using cosine similarity.
# 
# This function is applied to all embedding models unless the model
# output has already been normalized.
# 
# Parameters:
#   vector:
#       A one-dimensional embedding vector.
# 
# Returns:
#   The normalized embedding vector.
# ======================================================================

def normalize_vector(vector) -> np.ndarray:

    # Calculates the length or magnitude of the embedding vector.
    vector_norm = np.linalg.norm(vector)

    # A zero vector cannot be normalized because normalization requires
    # dividing every value in the vector by it magnitude.
    if vector_norm == 0:
        raise ValueError(
            "Error: The embedding vector cannot be normalized with zero magnitude."
        )
    
    return vector / vector_norm


# ======================================================================
# STEP 5. COMPUTE COSINE SIMILARITY
# 
# Computes the cosine similarity between one query embedding and all
# stored chunk embeddings.
# 
# Parameters:
#   query_embedding:
#       A one-dimensional query embedding.
# 
#   chunk_embeddings:
#       A two-dimensional array in which each row represents one chunk.
# 
# Returns:
#   A one-dimensional array that contains one similarity score per chunk.
# ======================================================================

def compute_cosine_similarities(query_embedding, chunk_embeddings) -> np.ndarray:

    query_embedding = normalize_vector(query_embedding)

    # --------- Normalizes the chunk embeddings ---------
    chunk_norms = np.linalg.norm(
        chunk_embeddings,
        axis=1,
        keepdims=True
    )

    if np.any(chunk_norms == 0):
        raise ValueError(
            "Error: There's chunk embedding that cannot be normalized since having zero magnitude."
        )
    
    normalized_chunk_embeddings = chunk_embeddings / chunk_norms

    # --------- Computes the dot produxt between the normalized query embedding
    #           and every normalized chunk embedding.                           ---------
    similarities = normalized_chunk_embeddings @ query_embedding

    return similarities


# ======================================================================
# STEP 6. RETRIEVE THE TOP-K CHUNKS.

# Retrieves the chunks with the highest cosine similarity scores for
# a given query.
# 
# Parameters:
#   query:
#       The question used for retrieval.
# 
#   embedding_model:
#       The embedding model used for both indexing and retrieval.
# 
#   chunking_method:
#       The chunking collection to search. 
#       {fixed_token, recursive, sentence, semantic}

#   model_resources:
#       The previously laoded model resources.
# 
#   top_k:
#       The number of highest-ranked chunks to return.
# 
# Returns:
#   A ranked list of retrieval records that contains each selected chunk,
#   its metadata, similarity score, and rank.
# ======================================================================

def dense_retrieve(query, embedding_model, chunking_method, model_resources, top_k):

    if embedding_model not in dense_indexes:
        raise ValueError(
            f"Error: Dense indexes do not contain model: {embedding_model}."
        )
    
    model_indexes = dense_indexes[embedding_model]

    if chunking_method not in model_indexes:
        raise ValueError(
            f"Error: Dense indexes do not contain chunking method: {chunking_method}"
        )
    
    # STEP 1: --------- Retrieves all chunk embeddings for one chuking method ---------
    # Selects the indexed chunks for the specified chunking method.
    indexed_chunks = model_indexes[chunking_method]

    # Stores the chunk records for later retrieval.
    chunks = indexed_chunks

    # Extracts all chunking embeddings and combines them into a NumPy array.
    chunk_embeddings = np.array(
        [
            chunk["embedding"]
            for chunk in indexed_chunks
        ],
        dtype=np.float32
    )

    if len(chunks) != len(chunk_embeddings):
        raise ValueError(
            "Error: The number of chunks does not match the number of chunk embeddings."
        )
    
    if top_k <= 0:
        raise ValueError(
            "Error: top_k must be greater than zero"
        )
    
    top_k = min(top_k, len(chunks))

    # STEP 2: --------- Generates the query embeddings using the selected model ---------
    query_embedding = get_query_embedding(
        query=query,
        embedding_model=embedding_model,
        model_resources=model_resources
    )

    if query_embedding.shape[0] != chunk_embeddings.shape[1]:
        raise ValueError(
            "Error: The query and chunk embeddings have different dimensions."
        )
    
    # STEP 3: --------- Computes one cosine similarity score for each chunk ---------
    similarity_scores = compute_cosine_similarities(
        query_embedding=query_embedding,
        chunk_embeddings=chunk_embeddings
    )

    # STEP 4: --------- Gets the indices of the top-k chunks in descending score order ---------
    top_indices = np.argsort(similarity_scores)[::-1][:top_k]

    # STEP 5: --------- Stores the ranked retrieval results ---------
    retrieval_results = []

    for rank, chunk_index in enumerate(top_indices, start=1):

        chunk = chunks[chunk_index]

        retrieval_results.append({
            "rank": rank,
            "similarity_score": float(similarity_scores[chunk_index]),
            "text": chunk["text"],
            "document_id": chunk["document_id"],
            "paper_id": chunk["paper_id"],
            "chunk_id": chunk["chunk_id"],
            "method": chunk["method"],
            "start": chunk["start"],
            "end": chunk["end"]
        })

    return retrieval_results


# ======================================================================
# STEP 7. TEST DENSE RETRIEVAL
#
# Prints the top-k (5) retrieved chunks for each query in `evaluation_questions.txt`.
# ======================================================================

if __name__ == "__main__":

    embedding_model = "BGE"
    chunking_method = "fixed_token"
    top_k = 5

    # Loads all evaluation questions from the JSON-formatted `evaluation_questions.txt`.
    with open("eval_qs_with_indices.txt", "r", encoding="utf-8") as file:
        evaluation_questions = json.load(file)

    # Loads the selected embedding model once and reuses it for all queries.
    model_resources = load_embedding_model(
        embedding_model=embedding_model
    )

    print(f"\n------ Top {top_k} dense retrieval results ------")

    # Performs dense retrieval for every evaluation question.
    for question_record in evaluation_questions:

        query = question_record["question"]

        results = dense_retrieve(
            query=query,
            embedding_model=embedding_model,
            chunking_method=chunking_method,
            model_resources=model_resources,
            top_k=top_k
        )

        question_id = question_record.get("question_id", "Missing question_id")
        paper_id = question_record.get("paper_id", "Missing paper_id")
        expected_answer = question_record.get("answer", "Missing answer")

        print(
            f"\n{'#' * 70}"
            f"\nQuestion ID: {question_id}"
            f"\nPaper ID: {paper_id}"
            f"\nEmbedding model: {embedding_model}"
            f"\nChunking method: {chunking_method}"
            f"\nQuery: {query}\n"
            f"\nExpected answer: {expected_answer}"
            f"\n{'#' * 70}\n"
        )

        for result in results:

            print("=" * 60)
            print(f"Rank: {result['rank']}")
            print(f"Similarity score: {result['similarity_score']}")
            print(f"Document ID: {result['document_id']}")
            print(f"Paper ID: {result['paper_id']}")
            print(f"Chunk ID: {result['chunk_id']}")
            print(f"Chunking Method: {result['method']}")
            print(f"Text:\n{result['text']}")